### ISSUE TITLE
Error: Model executable not found.

### ISSUE THREAD

**Issue by Frostjon** [stivalaa/culture_cooperation#1]
Dear:
       I download the project from github, when i  execute "mpirun --mca mpi_warn_on_fork 0 python ./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py m:100 F:5 strategy_update_rule:fermi culture_update_rule:fermi ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model 10000",    it return that "Model executable not found." .And I can not find "model" from the project I download /lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end.
     But  when I download the project from "https://sites.google.com/site/alexdstivala/home/culture_cooperation" ,there is "model" in it , and then i execute the same command, it said that "sh: ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model: cannot execute binary file".
    Looking forward for your help.
    Thanks.

**Comment by stivalaa** [comment]
''model" is an executable file, you have to either compile it (from the github source code) or use an already compiled version (like the one on my website). The UNIX (Linux) shell (sh) cannot execute such a binary file as if it were a shell script which is what the second error message means. The python script takes the location of the 'model' executable as an argument, so it has to be where you specified in that argument, which is what the first error message is saying (you had not compiled it, it wasn't in the location specified).

**Comment by Frostjon** [comment]
thanks for reply, now i am using the one on your website website not github, and i am sure that i have the 'model' in the right location that i specified in the command , and i got some error too.It is:

[zh@localhost ~]$ mpirun --mca mpi_warn_on_fork 0 python ./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py m:100 F:5 strategy_update_rule:fermi culture_update_rule:fermi ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model 10000
Psyco not installed or failed execution.
Using c++ version with  ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model
Psyco not installed or failed execution.
Using c++ version with  ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model
Psyco not installed or failed execution.
Using c++ version with  ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model
Psyco not installed or failed execution.
Using c++ version with  ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model
Clean start
Writing results to  results/10000/results0.csv
Clean start
Writing results to  results/10000/results2.csv
700 of total 700 models to run
175  models per MPI task
time series: writing total 70700 time step records
rank 0: 10000,30,10.000000,1.000000,0.000000,None,2,5,0.600000,0.000000,0
700 of total 700 models to run
175  models per MPI task
time series: writing total 70700 time step records
rank 2: 10000,30,10.000000,1.000000,0.000000,None,2,5,0.600000,0.000010,0
Clean start
Writing results to  results/10000/results3.csv
700 of total 700 models to run
175  models per MPI task
time series: writing total 70700 time step records
rank 3: 10000,30,10.000000,1.000000,0.000000,None,2,5,0.600000,0.000100,0
Clean start
Writing results to  results/10000/results1.csv
700 of total 700 models to run
175  models per MPI task
time series: writing total 70700 time step records
rank 1: 10000,30,10.000000,1.000000,0.000000,None,2,5,0.600000,0.000001,0
writeNetwork:  0.45688700676
writeNetwork:  0.474893093109
writeNetwork:  0.569287061691
writeNetwork:  0.680421113968
sh: ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model: cannot execute binary file
model:  0.0191311836243
writeNetwork:  0.555420875549
writeNetwork:  0.745272874832
sh: ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model: cannot execute binary file
model:  0.0191559791565
sh: ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model: cannot execute binary file
model:  0.0183458328247
writeNetwork:  1.0336060524
Traceback (most recent call last):
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 902, in <module>
    init_strategy)
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 551, in scenario
    k = 0.01, theta = theta, no_migration =no_migration, radius = radius, num_joint_activities = num_joint_activities, pool_multiplier = pool_multiplier, noise = noise, strategy_update_rule = strategy_update_rule, culture_update_rule = culture_update_rule) 
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 894, in modelCpp
    gamestats2 = loadGamestats(tmpdir + '/tmp.Gamestats')
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 802, in loadGamestats
    for line in open(filename):
IOError: [Errno 2] No such file or directory: '/tmp/expIhGDqS/tmp.Gamestats'
Traceback (most recent call last):
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 902, in <module>
    init_strategy)
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 551, in scenario
    k = 0.01, theta = theta, no_migration =no_migration, radius = radius, num_joint_activities = num_joint_activities, pool_multiplier = pool_multiplier, noise = noise, strategy_update_rule = strategy_update_rule, culture_update_rule = culture_update_rule) 
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 894, in modelCpp
    gamestats2 = loadGamestats(tmpdir + '/tmp.Gamestats')
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 802, in loadGamestats
    for line in open(filename):
IOError: [Errno 2] No such file or directory: '/tmp/expVwC40O/tmp.Gamestats'
Traceback (most recent call last):
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 902, in <module>
    init_strategy)
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 551, in scenario
    k = 0.01, theta = theta, no_migration =no_migration, radius = radius, num_joint_activities = num_joint_activities, pool_multiplier = pool_multiplier, noise = noise, strategy_update_rule = strategy_update_rule, culture_update_rule = culture_update_rule) 
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 894, in modelCpp
    gamestats2 = loadGamestats(tmpdir + '/tmp.Gamestats')
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 802, in loadGamestats
    for line in open(filename):
IOError: [Errno 2] No such file or directory: '/tmp/expAZnxhU/tmp.Gamestats'
writeNetwork:  1.2441740036
sh: ./lattice-jointactivity-simcoop-social-noise-constantmpcr-cpp-end/model: cannot execute binary file
model:  0.0289378166199
Traceback (most recent call last):
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 902, in <module>
    init_strategy)
  File "./lattice-python-mpi/src/axelrod/geo/expphysicstimeline/multiruninitmain.py", line 551, in scenario
    k = 0.01, theta = theta, no_migration =no_migration, radius = radius, num_joint_activities = num_joint_activities, pool_multiplier = pool_multiplier, noise = noise, strategy_update_rule = strategy_update_rule, culture_update_rule = culture_update_rule) 
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 894, in modelCpp
    gamestats2 = loadGamestats(tmpdir + '/tmp.Gamestats')
  File "/home/zh/lattice-python-mpi/src/axelrod/geo/lib.py", line 802, in loadGamestats
    for line in open(filename):
IOError: [Errno 2] No such file or directory: '/tmp/expPw37LR/tmp.Gamestats'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63412,1],3]
  Exit code:    1
--------------------------------------------------------------------------

what's more i run  'chmod 777 model', it has the same error.

Thank you very much!

**Comment by stivalaa** [comment]
Sorry there's nothing else I can tell from the output, you're going to have to get someone who knows how to use UNIX or Linux (whichever you are using) on your particular system to look at it.
